"""Thumbnail generation pipeline — Claude concepts + fal.ai images + FFmpeg compositing."""

import json
import os
import urllib.request
from pathlib import Path

from pydantic import BaseModel

from integrations.claude_client import chat
from integrations.fal_client import generate_image
from pipeline.ffmpeg_builder import build_thumbnail_composite_cmd

_data_dir = Path(os.environ.get("YAM_DATA_DIR", Path(__file__).resolve().parents[2] / "data"))

class ThumbnailConcept(BaseModel):
    """A single thumbnail concept generated by Claude."""

    visual_description: str
    title_text: str

SYSTEM_PROMPT = """\
You are a YouTube thumbnail designer. Generate thumbnail concepts that are \
eye-catching, high-contrast, and optimized for click-through rate.

Rules:
- Title text should be SHORT (2-5 words), punchy, and use power words.
- Visual description should describe a vivid, simple illustration that reads well at small sizes.
- Avoid clutter — thumbnails must be readable at 160x90 pixels.
- Return ONLY valid JSON — no markdown fences, no commentary.

Return a JSON array of objects with keys: visual_description, title_text.
"""

def generate_concepts(
    video_title: str,
    video_description: str = "",
    count: int = 3,
) -> list[ThumbnailConcept]:
    """Use Claude to generate thumbnail concepts for the video."""
    user_msg = f"Generate {count} thumbnail concepts for this YouTube video:\n\nTitle: {video_title}"
    if video_description:
        user_msg += f"\nDescription: {video_description}"

    raw = chat(SYSTEM_PROMPT, user_msg)
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        text = text.rsplit("```", 1)[0]

    data = json.loads(text)
    return [ThumbnailConcept.model_validate(item) for item in data]

def generate_thumbnail(
    script_id: str,
    idx: int,
    visual_description: str,
    title_text: str,
    brand_style: str = "",
    bar_color: str = "0x9333EA",
) -> str:
    """Generate a single thumbnail: fal.ai illustration + FFmpeg text composite.

    Returns the web-relative path to the final 1280x720 thumbnail.
    """
    prompt = f"{brand_style}. {visual_description}" if brand_style else visual_description

    cdn_url = generate_image(prompt, width=1280, height=720)

    # Download illustration
    thumbs_dir = _data_dir / "projects" / script_id / "renders" / "thumbnails"
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    raw_path = str(thumbs_dir / f"{idx}_raw.png")
    urllib.request.urlretrieve(cdn_url, raw_path)

    # Composite title text
    final_path = str(thumbs_dir / f"{idx}.png")
    import subprocess
    cmd = build_thumbnail_composite_cmd(
        image_path=raw_path,
        output_path=final_path,
        title_text=title_text,
        bar_color=bar_color,
    )
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Thumbnail composite failed: {result.stderr[-300:]}")

    # Clean up raw
    try:
        os.unlink(raw_path)
    except OSError:
        pass

    return f"/static/projects/{script_id}/renders/thumbnails/{idx}.png"
