"""Thumbnail generation pipeline — Claude concepts + Gemini images + FFmpeg compositing."""

import json
import logging
import os
import shutil
from pathlib import Path

from pydantic import BaseModel

from integrations.claude_client import chat
from integrations.google_image_client import generate_image
from pipeline.ffmpeg_builder import build_thumbnail_composite_cmd
from pipeline.video_render import copy_to_downloads, _sanitize_filename

log = logging.getLogger(__name__)

_data_dir = Path(os.environ.get("HH_DATA_DIR", os.environ.get("YAM_DATA_DIR", Path(__file__).resolve().parents[2] / "data")))

class ThumbnailConcept(BaseModel):
    """A single thumbnail concept generated by Claude."""

    visual_description: str
    title_text: str

SYSTEM_PROMPT = """\
You are a YouTube thumbnail designer. Generate thumbnail concepts that are \
eye-catching, high-contrast, and optimized for click-through rate.

Rules:
- Title text should be SHORT (2-5 words), punchy, and use power words.
- Visual description should describe a vivid, simple illustration that reads well at small sizes.
- Avoid clutter — thumbnails must be readable at 160x90 pixels.
- Return ONLY valid JSON — no markdown fences, no commentary.

Return a JSON array of objects with keys: visual_description, title_text.
"""

def generate_concepts(
    video_title: str,
    video_description: str = "",
    count: int = 3,
) -> list[ThumbnailConcept]:
    """Use Claude to generate thumbnail concepts for the video."""
    user_msg = f"Generate {count} thumbnail concepts for this YouTube video:\n\nTitle: {video_title}"
    if video_description:
        user_msg += f"\nDescription: {video_description}"

    raw = chat(SYSTEM_PROMPT, user_msg)
    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1]
        text = text.rsplit("```", 1)[0]

    data = json.loads(text)
    return [ThumbnailConcept.model_validate(item) for item in data]

def generate_thumbnail(
    script_id: str,
    idx: int,
    visual_description: str,
    title_text: str,
    brand_style: str = "",
    bar_color: str = "0x9333EA",
    title: str = "",
    font_family: str = "",
) -> str:
    """Generate a single thumbnail: Gemini illustration + FFmpeg text composite.

    Returns the web-relative path to the final 1280x720 thumbnail.
    """
    prompt = f"{brand_style}. {visual_description}" if brand_style else visual_description

    tmp_path = generate_image(prompt, width=1280, height=720)

    # Move illustration to renders directory
    thumbs_dir = _data_dir / "projects" / script_id / "renders" / "thumbnails"
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    raw_path = str(thumbs_dir / f"{idx}_raw.png")
    shutil.move(tmp_path, raw_path)

    # Composite title text
    final_path = str(thumbs_dir / f"{idx}.png")
    import subprocess
    cmd = build_thumbnail_composite_cmd(
        image_path=raw_path,
        output_path=final_path,
        title_text=title_text,
        bar_color=bar_color,
        font_family=font_family,
    )
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Thumbnail composite failed: {result.stderr[-300:]}")

    # Clean up raw
    try:
        os.unlink(raw_path)
    except OSError:
        pass

    web_path = f"/static/projects/{script_id}/renders/thumbnails/{idx}.png"

    if title:
        try:
            copy_to_downloads(title, final_path, f"{_sanitize_filename(title)} - Thumbnail {idx + 1}.png")
        except Exception:
            log.warning("Failed to copy thumbnail to downloads", exc_info=True)

    return web_path


def generate_shortform_thumbnail(
    script_id: str,
    idx: int,
    visual_description: str,
    title_text: str,
    brand_style: str = "",
    bar_color: str = "0x9333EA",
    title: str = "",
) -> str:
    """Generate a portrait 9:16 thumbnail for short-form video.

    Returns the web-relative path to the final thumbnail.
    """
    import subprocess

    prompt = f"{brand_style}. {visual_description}" if brand_style else visual_description
    prompt = f"Vertically composed portrait 9:16 image. {prompt}"

    tmp_path = generate_image(prompt, width=768, height=1344)

    thumbs_dir = _data_dir / "projects" / script_id / "renders" / "thumbnails"
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    raw_path = str(thumbs_dir / f"shortform_{idx}_raw.png")
    shutil.move(tmp_path, raw_path)

    # Composite: scale to 1080x1920, add text at 40% height, brand bar at bottom
    final_path = str(thumbs_dir / f"shortform_{idx}.png")

    from pipeline.ffmpeg_builder import _escape_drawtext, _DRAWTEXT_AVAILABLE

    escaped = _escape_drawtext(title_text)
    vf = (
        f"scale=1080:1920:force_original_aspect_ratio=decrease,"
        f"pad=1080:1920:(ow-iw)/2:(oh-ih)/2:black,"
        f"drawbox=x=0:y=ih-100:w=iw:h=100:color=#{bar_color.replace('0x', '')}@0.85:t=fill"
    )

    if _DRAWTEXT_AVAILABLE:
        vf += (
            f",drawtext=text='{escaped}':fontsize=64:fontcolor=white"
            f":x=(w-text_w)/2:y=h*0.40"
            f":borderw=3:bordercolor=black"
            f":shadowx=3:shadowy=3:shadowcolor='black@0.7'"
        )

    cmd = [
        "ffmpeg", "-y",
        "-i", raw_path,
        "-vf", vf,
        "-frames:v", "1",
        final_path,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Shortform thumbnail composite failed: {result.stderr[-300:]}")

    try:
        os.unlink(raw_path)
    except OSError:
        pass

    web_path = f"/static/projects/{script_id}/renders/thumbnails/shortform_{idx}.png"

    if title:
        try:
            copy_to_downloads(title, final_path, f"{_sanitize_filename(title)} - Shortform Thumbnail {idx + 1}.png")
        except Exception:
            log.warning("Failed to copy shortform thumbnail to downloads", exc_info=True)

    return web_path
