"""Thumbnail generation pipeline — Claude concepts + Gemini images + FFmpeg compositing.

When the title_cards modifier is active and a composite title card exists,
it is used directly as the thumbnail instead of generating a new one.
"""

import json
import logging
import os
import shutil
from pathlib import Path

from pydantic import BaseModel

from config import DATA_DIR, THUMBNAIL_HEIGHT, THUMBNAIL_WIDTH, sanitize_filename, strip_markdown_fences
from integrations.claude_client import chat
from integrations.google_image_client import generate_image
from pipeline.ffmpeg_builder import build_thumbnail_composite_cmd
from pipeline.video_render import copy_to_downloads

logger = logging.getLogger(__name__)

class ThumbnailConcept(BaseModel):
    """A single thumbnail concept generated by Claude."""

    visual_description: str
    title_text: str

SYSTEM_PROMPT = """\
You are a YouTube thumbnail designer. Generate thumbnail concepts that are \
eye-catching, high-contrast, and optimized for click-through rate.

Rules:
- Title text should be SHORT (2-5 words), punchy, and use power words.
- Visual description should describe a vivid, simple illustration that reads well at small sizes.
- Avoid clutter — thumbnails must be readable at 160x90 pixels.
- Return ONLY valid JSON — no markdown fences, no commentary.

Return a JSON array of objects with keys: visual_description, title_text.
"""

def generate_concepts(
    video_title: str,
    video_description: str = "",
    count: int = 3,
    script_id: str | None = None,
) -> list[ThumbnailConcept]:
    """Use Claude to generate thumbnail concepts for the video."""
    logger.info("Generating %s thumbnail concepts for %r", count, video_title)
    user_msg = f"Generate {count} thumbnail concepts for this YouTube video:\n\nTitle: {video_title}"
    if video_description:
        user_msg += f"\nDescription: {video_description}"

    raw = chat(SYSTEM_PROMPT, user_msg, script_id=script_id)
    text = strip_markdown_fences(raw)

    data = json.loads(text)
    concepts = [ThumbnailConcept.model_validate(item) for item in data]
    logger.info("Generated %s thumbnail concepts for %r", len(concepts), video_title)
    return concepts

def get_composite_thumbnail(script_id: str) -> str | None:
    """Check if a composite title card exists and return its web path if so."""
    composite = DATA_DIR / "projects" / script_id / "images" / "composite_title_card.png"
    if composite.exists():
        # Copy to thumbnail location
        thumbs_dir = DATA_DIR / "projects" / script_id / "renders" / "thumbnails"
        thumbs_dir.mkdir(parents=True, exist_ok=True)
        thumb_path = thumbs_dir / "0.png"
        shutil.copy2(str(composite), str(thumb_path))
        return f"/static/projects/{script_id}/renders/thumbnails/0.png"
    return None


def generate_thumbnail(
    script_id: str,
    idx: int,
    visual_description: str,
    title_text: str,
    bar_color: str = "0x9333EA",
    title: str = "",
    font_family: str = "",
) -> str:
    """Generate a single thumbnail: Gemini illustration + FFmpeg text composite.

    Returns the web-relative path to the final 1280x720 thumbnail.
    """
    logger.info("Generating thumbnail %s for script %s", idx, script_id)
    prompt = visual_description

    tmp_path = generate_image(prompt, width=THUMBNAIL_WIDTH, height=THUMBNAIL_HEIGHT, script_id=script_id)

    # Move illustration to renders directory
    thumbs_dir = DATA_DIR / "projects" / script_id / "renders" / "thumbnails"
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    raw_path = str(thumbs_dir / f"{idx}_raw.png")
    shutil.move(tmp_path, raw_path)

    # Composite title text
    final_path = str(thumbs_dir / f"{idx}.png")
    import subprocess
    cmd = build_thumbnail_composite_cmd(
        image_path=raw_path,
        output_path=final_path,
        title_text=title_text,
        bar_color=bar_color,
        font_family=font_family,
    )
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        raise RuntimeError(f"Thumbnail composite failed: {result.stderr[-300:]}")

    # Clean up raw
    try:
        os.unlink(raw_path)
    except OSError:
        pass

    web_path = f"/static/projects/{script_id}/renders/thumbnails/{idx}.png"
    logger.info("Thumbnail %s generated for script %s", idx, script_id)

    if title:
        try:
            copy_to_downloads(title, final_path, f"{sanitize_filename(title)} - Thumbnail {idx + 1}.png")
        except Exception:
            logger.warning("Failed to copy thumbnail to downloads", exc_info=True)

    return web_path
