"""Pydantic models for the auto-editing timeline generated by Claude."""

from pydantic import BaseModel


class WordTimestamp(BaseModel):
    """A single word with its timing from TTS alignment."""

    word: str
    start_ms: int
    end_ms: int


class TextPhrase(BaseModel):
    """A group of 3-5 words shown on screen simultaneously."""

    words: list[str]
    start_ms: int
    end_ms: int
    highlight_color: str = "#00FFFF"


class SFXTrigger(BaseModel):
    """An SFX trigger point — stored in timeline but not executed in v1."""

    category: str  # impact | ui | accent | microdrop | transition
    trigger_time_ms: int
    selection: str = "random"


class SceneTimeline(BaseModel):
    """Editing decisions for a single scene."""

    scene_id: str
    motion_profile: str  # slow_zoom_in | slow_zoom_out | slow_pan
    transition: str = "hard_cut"  # hard_cut | dip_to_black
    text_phrases: list[TextPhrase] = []
    sfx_triggers: list[SFXTrigger] = []


class AutoEditTimeline(BaseModel):
    """Full editing timeline for all scenes, generated by Claude."""

    accent_color: str = "#00FFFF"
    scenes: list[SceneTimeline]
